version: '3'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3300:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: password
